# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-26 08:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190326_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 8, 58, 50, 239887, tzinfo=utc)),
        ),
    ]
