# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-26 09:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190326_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_column2', to='article.ArticleColumn'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 9, 35, 9, 432269, tzinfo=utc)),
        ),
    ]
