# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-26 09:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190326_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 9, 39, 27, 919258, tzinfo=utc)),
        ),
    ]
