# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-12 01:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20190412_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecolumn',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ('updated',)},
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 1, 27, 3, 32259, tzinfo=utc)),
        ),
    ]
